### ISSUE TITLE
only have ios Development certificate,can't run

### ISSUE THREAD

**Issue by icefox57** [onmyway133/XcodeWay#17]
get error No signing certificate "Mac Development"
is there any way ?

**Comment by onmyway133** [comment]
@icefox57 Hi, can you use the release from https://github.com/onmyway133/XcodeWay/releases/tag/1.1.0
Also, in order to build, you need a certificate https://developer.apple.com/support/certificates/
![codesign](https://cloud.githubusercontent.com/assets/2284279/26819051/821fd774-4a9d-11e7-9ffb-de20b77870f2.png)
